name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        
    - name: Cache Node.js modules
      uses: actions/cache@v3
      with:
        path: ./monendovue.client/node_modules
        key: ${{ runner.os }}-node-modules-${{ hashFiles('./monendovue.client/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-modules-

    - name: Install dependencies
      run: npm install
      working-directory: ./monendovue.client

    - name: Install Playwright browsers
      run: npx playwright install --with-deps
      working-directory: ./monendovue.client

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Cache NuGet packages
      uses: actions/cache@v3
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
        restore-keys: |
          ${{ runner.os }}-nuget- 

    - name: Run ESLint
      run: npx eslint . --ext .ts,.js
      working-directory: ./monendovue.client
      continue-on-error: true

    - name: Build .NET project
      run: dotnet build --configuration Release

    - name: Run Playwright tests
      run: npm run test:e2e
      working-directory: ./monendovue.client

    - name: Publish build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-output
        path: ./monendovue.client/dist
